services:
  localstack:
    image: localstack/localstack
    container_name: items_localstack
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - DEBUG=${DEBUG:-1}
      - SERVICES=dynamodb,lambda,iam,apigateway
      - PERSISTENCE=1
      - DEFAULT_REGION=eu-north-1
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"